name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Job 1: Run Unit Tests on PR
  tests:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Run Codegen
        run: bun run codegen

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Run Unit Tests
        run: bun run test

      - name: Run Integration Tests
        run: bun run test:e2e

  # Job 2: Apply Database Changes with Prisma when code is merged to main
  db-push:
    name: Push DB Changes with Prisma
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Apply DB changes
        run: bunx prisma db push
