name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Job 1: Run Unit Tests on PR
  tests:
    name: Test
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Run Unit Tests (Isolated)
        run: bash scripts/run-isolated-tests.sh Unit
        # This script runs each test file individually to work around Bun's mock.module() bug
        # See: https://github.com/oven-sh/bun/issues/7823

      - name: Run Integration Tests (Isolated)
        run: bash scripts/run-isolated-tests.sh E2E

  # Job 2: Apply Database Changes with Prisma when code is merged to main
  db-push:
    name: Push DB Changes with Prisma
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Apply DB changes
        run: bunx prisma db push
